### ISSUE TITLE
"String.length()" because "s" is null

### ISSUE THREAD

**Issue by MrRoooo** [HughBone/fabrilous-updater#15]
When I run the updater in game, I got tons of "String.length()" because "s" is null error while using MultiMC.

[13:22:43] [Thread-8/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[13:22:43] [Thread-8/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[13:22:43] [Thread-8/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[13:22:43] [Thread-8/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[13:22:43] [Thread-8/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[13:22:43] [Thread-8/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:53)
[13:22:43] [Thread-8/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.UpdateCommand$StartThread.run(UpdateCommand.java:60)

**Comment by Boobies** [comment]
Would be great if this got fixed cause my logs always have a lot of this crud in them.
