### ISSUE TITLE
cannot update Fabric mods 1.18.2

### ISSUE THREAD

**Issue by Lassilos** [HughBone/fabrilous-updater#24]
[19:59:09] [Thread-33/INFO]: [CHAT] [Fabrilous Updater] Automatically updating all mods...
[19:59:10] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[19:59:10] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[19:59:10] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[19:59:10] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[19:59:10] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[19:59:10] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[19:59:10] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[19:59:19] [Thread-33/INFO]: [STDERR]: java.nio.file.FileSystemException: C:\Users\Lasse\AppData\Roaming\.minecraft\mods\architectury-4.0.30.jar: The process cannot access the file because it is being used by another process
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.delete(Files.java:1152)
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:94)
[19:59:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[19:59:19] [Thread-33/INFO]: [CHAT] Architectury API: [2022-03-04] --> [2022-04-02]
[19:59:20] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[19:59:20] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[19:59:20] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[19:59:20] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[19:59:21] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[19:59:21] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[19:59:21] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[19:59:21] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[19:59:21] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[19:59:21] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[19:59:21] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[19:59:22] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[19:59:22] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[19:59:22] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[19:59:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[19:59:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[19:59:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[19:59:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[19:59:44] [Server thread/INFO]: Saving and pausing game...
[19:59:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing world]'/minecraft:overworld
[19:59:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing world]'/minecraft:the_end
[19:59:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing world]'/minecraft:the_nether
[19:59:45] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[19:59:45] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[19:59:45] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[19:59:45] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[19:59:45] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[19:59:45] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[19:59:45] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:09] [Render thread/INFO]: [CHAT] [Warning] This command automatically downloads new versions and moves old mods into the 'Outdated_Mods' folder. Click here to continue.
[20:00:11] [Thread-35/INFO]: [CHAT] [Error] Already checking for updates!
[20:00:16] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:16] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:16] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:16] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:19] [Thread-33/INFO]: [STDERR]: java.nio.file.FileSystemException: C:\Users\Lasse\AppData\Roaming\.minecraft\mods\fabric-api-0.47.10+1.18.2.jar: The process cannot access the file because it is being used by another process
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.delete(Files.java:1152)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:94)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:19] [Thread-33/INFO]: [CHAT] Fabric API: [2022-03-05] --> [2022-03-13]
[20:00:19] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:19] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:20] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:20] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:20] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:20] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:22] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:00:22] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:00:22] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:00:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:00:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:00:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:23] [Thread-33/INFO]: [STDERR]: java.nio.file.FileSystemException: C:\Users\Lasse\AppData\Roaming\.minecraft\mods\FpsReducer-fabric-1.25-mc1.18.jar: The process cannot access the file because it is being used by another process
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.delete(Files.java:1152)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:94)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:23] [Thread-33/INFO]: [CHAT] FPS Reducer: [2021-12-04] --> [2022-03-07]
[20:00:23] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:26] [Server thread/INFO]: Saving and pausing game...
[20:00:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing world]'/minecraft:overworld
[20:00:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing world]'/minecraft:the_end
[20:00:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Testing world]'/minecraft:the_nether
[20:00:30] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:00:30] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:00:30] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:00:30] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:00:30] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:00:30] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:30] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:32] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:00:32] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:00:32] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:00:32] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:00:32] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:00:32] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:32] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:33] [Thread-33/INFO]: [STDERR]: java.nio.file.FileSystemException: C:\Users\Lasse\AppData\Roaming\.minecraft\mods\litematica-fabric-1.18.2-0.11.0.jar: The process cannot access the file because it is being used by another process
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.delete(Files.java:1152)
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:94)
[20:00:33] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:33] [Thread-33/INFO]: [CHAT] Litematica: [2022-03-03] --> [2022-03-13]
[20:00:34] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:34] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:34] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:34] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:35] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:35] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:35] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:37] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:00:37] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:00:37] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:00:37] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:00:37] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:00:37] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:37] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:38] [Thread-33/INFO]: [STDERR]: java.nio.file.FileSystemException: C:\Users\Lasse\AppData\Roaming\.minecraft\mods\malilib-fabric-1.18.2-0.12.0.jar: The process cannot access the file because it is being used by another process
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.delete(Files.java:1152)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:94)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:38] [Thread-33/INFO]: [CHAT] MaLiLib: [2022-03-03] --> [2022-03-13]
[20:00:38] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:38] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:51] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:51] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:51] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:51] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:55] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:55] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:55] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:55] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:00:58] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:00:58] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:00:58] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:00:58] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:01:06] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:01:06] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:01:06] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:01:06] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:01:06] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:01:06] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:01:06] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:01:09] [Thread-33/INFO]: [STDERR]: java.nio.file.FileSystemException: C:\Users\Lasse\AppData\Roaming\.minecraft\mods\RoughlyEnoughItems-8.0.442.jar: The process cannot access the file because it is being used by another process
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.delete(Files.java:1152)
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:94)
[20:01:09] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:01:09] [Thread-33/INFO]: [CHAT] Roughly Enough Items Fabric/Forge (REI): [2022-03-03] --> [2022-03-03]
[20:01:10] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:01:10] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:01:10] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:01:10] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:01:22] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[20:01:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[20:01:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:01:22] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:01:23] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:01:23] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:01:23] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:01:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:01:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:01:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:01:23] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:01:44] [Thread-33/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[20:01:44] [Thread-33/INFO]: [STDERR]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[20:01:44] [Thread-33/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
[20:01:44] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.util.FabUtil.getJsonObject(FabUtil.java:105)
[20:01:44] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:31)
[20:01:44] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[20:01:44] [Thread-33/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81)
[20:01:47] [Thread-33/INFO]: [CHAT] [FabrilousUpdater] Finished! Restart Minecraft to apply updates.

**Comment by wb1016** [comment]
duplicate of #15
