### ISSUE TITLE
'fabdateserver autoupdate' command does not work

### ISSUE THREAD

**Issue by wb1016** [HughBone/fabrilous-updater#25]
enviroment: fabric api 0.52.0~0.53.0\
log output
```
[10:53:31] [Thread-1344/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[10:53:31] [Thread-1344/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.CurrentMod.<init>(CurrentMod.java:32)
[10:53:31] [Thread-1344/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.platform.ModPlatform.start(ModPlatform.java:58)
[10:53:31] [Thread-1344/INFO]: [STDERR]: 	at com.hughbone.fabrilousupdater.command.AutoUpdateCommand$StartThread.run(AutoUpdateCommand.java:81) 
```

**Comment by ST-DDT** [comment]
Maybe curse updated their API?

**Comment by wb1016** [comment]
> Maybe curse updated their API?

nah, it cant get mods from modrinth too. seems about some kind of dependency issue.
