### ISSUE TITLE
API problems

### ISSUE THREAD

**Issue by mllightitup** [HughBone/fabrilous-updater#26]
This API: https://curseapidoc.docs.apiary.io/ doesn't work for some reason.
Maybe you should switch to the official curseforge api: https://docs.curseforge.com/#getting-started
But the problem is that you need your own api key and putting it in the public domain is not the best idea
Also, modrinth have updated their api to version v2: https://docs.modrinth.com/

**Comment by mllightitup** [comment]
> well this sucks

I updated all the API and moved the mod to 1.19
Perhaps something might not work, because I have not tested all the functions and I do not know Java :)))
"/fabdate update" - works correctly
https://github.com/mllightitup/fabrilous-updater

**Comment by HughBone** [comment]
Based

**Comment by Atticuss320** [comment]
thank you so much

**Comment by mllightitup** [comment]
> thank you so much

Be careful. This mod does not always work correctly with Quilt and finds incorrect updates if you play NOT on the latest minor version of minecraft (For example, on 1.18.2 everything will be fine, but on 1.18.1 it may find the wrong version).
This is especially noticeable now with 1.19, 1.19.1, 1.19.2.
So I recommend double checking to avoid errors.

**Comment by Atticuss320** [comment]
is there a way to fix this in the future

**Comment by mllightitup** [comment]
> is there a way to fix this in the future

There is a way, but I can not because I do not know java enough and how to work with fabric. In general, I'm not a developer of mods)) I think that someone who knows java on a basic to average level can easily fix it.

For mods from modrinth you just need to change the way you get the update information. The modrinth api documentation has a way to get updates more accurately: https://docs.modrinth.com/api-spec/#tag/version-files/operation/getLatestVersionFromHash

Curseforge is more complicated, need to look into it

**Comment by Atticuss320** [comment]
will you update it to 1.19.3 when it releases?

**Comment by Atticuss320** [comment]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabrilousupdater'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/mojang/bridge/game/GameVersion
	at com.hughbone.fabrilousupdater.command.IgnoreCommand.removeDeletedMods(IgnoreCommand.java:62)
	at com.hughbone.fabrilousupdater.command.IgnoreCommand.register(IgnoreCommand.java:32)
	at com.hughbone.fabrilousupdater.FabrilousUpdater.onInitialize(FabrilousUpdater.java:21)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.mojang.bridge.game.GameVersion
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
